### ISSUE TITLE
Initiate blockchain part

### ISSUE THREAD

**Issue by ShivRaiGithub** [Meghnagit20/LegaLINc#8]
I would like to start the project by using Foundry to setup the base.

**Comment by Meghnagit20** [comment]
Hello, Sure. I have actually discontinued this project due to some other
important commitments. However, if you interested in this one, we can
connect on LinkedIn and proceed.

**Comment by ShivRaiGithub** [comment]
Oh, I wanted to contribute since this was listed as one of the projects of gs wob.
